EW-179: Modified blog
evonove/evonove.it pull request #58
Opened 2017-07-28 10:31 UTC by Girbons

### What it does

- Over the post is now visible the user gravatar
- Below each post are now available a maximum of 3 similar posts that match the post tags

2017-07-28 11:01 UTC, Alien1993 commented on django-website/blog/models.py
> +        context['similar_articles'] = similar_articles[:3]
We don't really need to loop every article if we only need the last 3.

2017-07-28 11:01 UTC, silvanocerza requested changes
Check comments

2017-07-28 11:03 UTC, Girbons commented on django-website/blog/models.py
> +        context['similar_articles'] = similar_articles[:3]
Are you sure?

2017-07-28 11:05 UTC, Alien1993 commented on django-website/blog/models.py
> +        context['similar_articles'] = similar_articles[:3]
Oh right, you need to check the tags for each one. Nevermind.

2017-07-28 11:06 UTC, silvanocerza approved these changes

2017-08-01 12:57 UTC, Psykopear approved these changes

2017-08-01 13:08 UTC, merged